spring.application.name=manneger


# KEYS JWT - SECURITY
jwt.secret=mySecretKey
jwt.expiration=3600000

# POSTGRESS
spring.datasource.url=jdbc:postgresql://localhost:5430/trinity-auth-service
spring.datasource.username=tryuser
spring.datasource.password=12s32sa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger-ui.html